const {
  AWS_REGION,
  S3_BUCKET,
  S3_SNAPSHOT = 'snapshots',
  S3_ORIGINAL_IMAGES = 'original_images',
  S3_TAMPERING_REF = 'tampering-ref',
  DYNAMODB_ANALYSIS_RESULTS_TABLE,
  DYNAMODB_ANALYSIS_RESULTS_QUERY_LIMIT = 500,
  DYNAMODB_ANALYSIS_RESULTS_RESULT_LIMIT = 50,
  REDSHIFT_WORKGROUP = 'non-prod',
  REDSHIFT_DATABASE = 'dev',
  REDSHIFT_ANNOTATIONS_TABLE,
} = process.env

const queryLimit = Number.parseInt(DYNAMODB_ANALYSIS_RESULTS_QUERY_LIMIT, 10)
const resultLimit = Number.parseInt(DYNAMODB_ANALYSIS_RESULTS_RESULT_LIMIT, 10)

export {
  AWS_REGION,
  S3_BUCKET,
  S3_SNAPSHOT,
  S3_ORIGINAL_IMAGES,
  S3_TAMPERING_REF,
  DYNAMODB_ANALYSIS_RESULTS_TABLE,
  queryLimit as DYNAMODB_ANALYSIS_RESULTS_QUERY_LIMIT,
  resultLimit as DYNAMODB_ANALYSIS_RESULTS_RESULT_LIMIT,
  REDSHIFT_WORKGROUP,
  REDSHIFT_DATABASE,
  REDSHIFT_ANNOTATIONS_TABLE,
}
